openapi: 3.0.0
info:
  title: Node.js Express typescript Boilerplate
  description: A boilerplate for Node.js Express typescript
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /:
    get:
      summary: Hello world
      description: Hello world
      tags:
        - Hello world
      responses:
        "200":
          description: Hello world
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello world!"
